config/routes.rb
Rails.application.routes.draw do
  resources :mes

  resources :cols

   root 'mes#index'

end

app/models/col.rb
class Col < ActiveRecord::Base
end

app/models/me.rb
class Me < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cols_controller.rb
class ColsController < ApplicationController
  before_action :set_col, only: [:show, :edit, :update, :destroy]

  # GET /cols
  # GET /cols.json
  def index
    @cols = Col.all
  end

  # GET /cols/1
  # GET /cols/1.json
  def show
  end

  # GET /cols/new
  def new
    @col = Col.new
  end

  # GET /cols/1/edit
  def edit
  end

  # POST /cols
  # POST /cols.json
  def create
    @col = Col.new(col_params)

    respond_to do |format|
      if @col.save
        format.html { redirect_to @col, notice: 'Col was successfully created.' }
        format.json { render :show, status: :created, location: @col }
      else
        format.html { render :new }
        format.json { render json: @col.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cols/1
  # PATCH/PUT /cols/1.json
  def update
    respond_to do |format|
      if @col.update(col_params)
        format.html { redirect_to @col, notice: 'Col was successfully updated.' }
        format.json { render :show, status: :ok, location: @col }
      else
        format.html { render :edit }
        format.json { render json: @col.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cols/1
  # DELETE /cols/1.json
  def destroy
    @col.destroy
    respond_to do |format|
      format.html { redirect_to cols_url, notice: 'Col was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_col
      @col = Col.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def col_params
      params.require(:col).permit(:name, :age, :sub)
    end
end

app/controllers/mes_controller.rb
class MesController < ApplicationController
  before_action :set_me, only: [:show, :edit, :update, :destroy]

  # GET /mes
  # GET /mes.json
  def index
    @mes = Me.all
  end

  # GET /mes/1
  # GET /mes/1.json
  def show
  end

  # GET /mes/new
  def new
    @me = Me.new
  end

  # GET /mes/1/edit
  def edit
  end

  # POST /mes
  # POST /mes.json
  def create
    @me = Me.new(me_params)

    respond_to do |format|
      if @me.save
        format.html { redirect_to @me, notice: 'Me was successfully created.' }
        format.json { render :show, status: :created, location: @me }
      else
        format.html { render :new }
        format.json { render json: @me.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mes/1
  # PATCH/PUT /mes/1.json
  def update
    respond_to do |format|
      if @me.update(me_params)
        format.html { redirect_to @me, notice: 'Me was successfully updated.' }
        format.json { render :show, status: :ok, location: @me }
      else
        format.html { render :edit }
        format.json { render json: @me.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mes/1
  # DELETE /mes/1.json
  def destroy
    @me.destroy
    respond_to do |format|
      format.html { redirect_to mes_url, notice: 'Me was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_me
      @me = Me.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def me_params
      params.require(:me).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cols_helper.rb
module ColsHelper
end

app/helpers/mes_helper.rb
module MesHelper
end

app/views/cols/_form.html.erb
<%= form_for(@col) do |f| %>
  <% if @col.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@col.errors.count, "error") %> prohibited this col from being saved:</h2>

      <ul>
      <% @col.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :sub %><br>
    <%= f.text_field :sub %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cols/edit.html.erb
<h1>Editing col</h1>

<%= render 'form' %>

<%= link_to 'Show', @col %> |
<%= link_to 'Back', cols_path %>

app/views/cols/index.html.erb
<h1>Listing cols</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Sub</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cols.each do |col| %>
      <tr>
        <td><%= col.name %></td>
        <td><%= col.age %></td>
        <td><%= col.sub %></td>
        <td><%= link_to 'Show', col %></td>
        <td><%= link_to 'Edit', edit_col_path(col) %></td>
        <td><%= link_to 'Destroy', col, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Col', new_col_path %>

app/views/cols/new.html.erb
<h1>New col</h1>

<%= render 'form' %>

<%= link_to 'Back', cols_path %>

app/views/cols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @col.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @col.age %>
</p>

<p>
  <strong>Sub:</strong>
  <%= @col.sub %>
</p>

<%= link_to 'Edit', edit_col_path(@col) %> |
<%= link_to 'Back', cols_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestotron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mes/_form.html.erb
<%= form_for(@me) do |f| %>
  <% if @me.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@me.errors.count, "error") %> prohibited this me from being saved:</h2>

      <ul>
      <% @me.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mes/edit.html.erb
<h1>Editing me</h1>

<%= render 'form' %>

<%= link_to 'Show', @me %> |
<%= link_to 'Back', mes_path %>

app/views/mes/index.html.erb
<h1>Listing mes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mes.each do |me| %>
      <tr>
        <td><%= me.name %></td>
        <td><%= me.age %></td>
        <td><%= link_to 'Show', me %></td>
        <td><%= link_to 'Edit', edit_me_path(me) %></td>
        <td><%= link_to 'Destroy', me, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Me', new_me_path %>

app/views/mes/new.html.erb
<h1>New me</h1>

<%= render 'form' %>

<%= link_to 'Back', mes_path %>

app/views/mes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @me.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @me.age %>
</p>

<%= link_to 'Edit', edit_me_path(@me) %> |
<%= link_to 'Back', mes_path %>